language: csharp
solution: "./MyQA/MyQA.sln"
install:
  - nuget restore ./MyQA/MyQA.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release solution-name.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./MyQA/MyQADLL.test/bin/Release/./MyQA/MyQADLL.test.dll