
// This file has been generated by the GUI designer. Do not modify.
namespace MyQA.view
{
	public partial class QuestionScreen
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.Image background;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MyQA.view.QuestionScreen
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 800;
			this.HeightRequest = 600;
			this.Name = "MyQA.view.QuestionScreen";
			// Container child MyQA.view.QuestionScreen.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.background = new global::Gtk.Image();
			this.background.WidthRequest = 800;
			this.background.HeightRequest = 600;
			this.background.Name = "background";
			this.fixed3.Add(this.background);
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
