
// This file has been generated by the GUI designer. Do not modify.
namespace MyQA.view
{
	public partial class UserInput
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MyQA.view.UserInput
			this.WidthRequest = 800;
			this.HeightRequest = 600;
			this.Name = "MyQA.view.UserInput";
			this.Title = global::Mono.Unix.Catalog.GetString("Question and Answer Game");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 8000;
			this.DefaultHeight = 600;
			this.Show();
		}
	}
}
