
// This file has been generated by the GUI designer. Do not modify.
namespace MyQA.view
{
	public partial class TitleScreen
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.Image background;

		private global::Gtk.Button playBtn;

		private global::Gtk.Button historyBtn;

		private global::Gtk.Button exitBtn;

		private global::Gtk.Image welcome;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MyQA.view.TitleScreen
			this.WidthRequest = 800;
			this.HeightRequest = 600;
			this.Name = "MyQA.view.TitleScreen";
			this.Title = global::Mono.Unix.Catalog.GetString("Question and Answer Game");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Container child MyQA.view.TitleScreen.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.background = new global::Gtk.Image();
			this.background.WidthRequest = 800;
			this.background.HeightRequest = 600;
			this.background.Name = "background";
			this.fixed2.Add(this.background);
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.playBtn = new global::Gtk.Button();
			this.playBtn.WidthRequest = 110;
			this.playBtn.HeightRequest = 50;
			this.playBtn.CanFocus = true;
			this.playBtn.Name = "playBtn";
			this.fixed2.Add(this.playBtn);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.playBtn]));
			w2.X = 350;
			w2.Y = 250;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.historyBtn = new global::Gtk.Button();
			this.historyBtn.WidthRequest = 110;
			this.historyBtn.HeightRequest = 50;
			this.historyBtn.CanFocus = true;
			this.historyBtn.Name = "historyBtn";
			this.fixed2.Add(this.historyBtn);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.historyBtn]));
			w3.X = 350;
			w3.Y = 320;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.exitBtn = new global::Gtk.Button();
			this.exitBtn.WidthRequest = 110;
			this.exitBtn.HeightRequest = 50;
			this.exitBtn.CanFocus = true;
			this.exitBtn.Name = "exitBtn";
			this.fixed2.Add(this.exitBtn);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.exitBtn]));
			w4.X = 350;
			w4.Y = 390;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.welcome = new global::Gtk.Image();
			this.welcome.WidthRequest = 500;
			this.welcome.HeightRequest = 100;
			this.welcome.Name = "welcome";
			this.fixed2.Add(this.welcome);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.welcome]));
			w5.X = 150;
			w5.Y = 130;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 600;
			this.Show();
			this.exitBtn.Clicked += new global::System.EventHandler(this.ClickToExit);
		}
	}
}
