
// This file has been generated by the GUI designer. Do not modify.
namespace MyQA.view
{
	public partial class ResultScreen
	{
		private global::Gtk.Fixed fixed4;

		private global::Gtk.Image background;

		private global::Gtk.Button playAgainBtn;

		private global::Gtk.Button quitBtn;

		private global::Gtk.Label gameoverLabel;

		private global::Gtk.Label playerScore;

		private global::Gtk.Label botScore;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MyQA.view.ResultScreen
			global::Stetic.BinContainer.Attach(this);
			this.WidthRequest = 800;
			this.HeightRequest = 600;
			this.Name = "MyQA.view.ResultScreen";
			// Container child MyQA.view.ResultScreen.Gtk.Container+ContainerChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.background = new global::Gtk.Image();
			this.background.WidthRequest = 800;
			this.background.HeightRequest = 600;
			this.background.Name = "background";
			this.fixed4.Add(this.background);
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.playAgainBtn = new global::Gtk.Button();
			this.playAgainBtn.WidthRequest = 110;
			this.playAgainBtn.HeightRequest = 50;
			this.playAgainBtn.CanFocus = true;
			this.playAgainBtn.Name = "playAgainBtn";
			this.fixed4.Add(this.playAgainBtn);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.playAgainBtn]));
			w2.X = 250;
			w2.Y = 350;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.quitBtn = new global::Gtk.Button();
			this.quitBtn.WidthRequest = 110;
			this.quitBtn.HeightRequest = 50;
			this.quitBtn.CanFocus = true;
			this.quitBtn.Name = "quitBtn";
			this.fixed4.Add(this.quitBtn);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.quitBtn]));
			w3.X = 400;
			w3.Y = 350;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.gameoverLabel = new global::Gtk.Label();
			this.gameoverLabel.WidthRequest = 700;
			this.gameoverLabel.HeightRequest = 50;
			this.gameoverLabel.Name = "gameoverLabel";
			this.gameoverLabel.LabelProp = global::Mono.Unix.Catalog.GetString("label33");
			this.gameoverLabel.Justify = ((global::Gtk.Justification)(2));
			this.fixed4.Add(this.gameoverLabel);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.gameoverLabel]));
			w4.X = 50;
			w4.Y = 150;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.playerScore = new global::Gtk.Label();
			this.playerScore.WidthRequest = 500;
			this.playerScore.HeightRequest = 50;
			this.playerScore.Name = "playerScore";
			this.playerScore.LabelProp = global::Mono.Unix.Catalog.GetString("label34");
			this.playerScore.Justify = ((global::Gtk.Justification)(2));
			this.fixed4.Add(this.playerScore);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.playerScore]));
			w5.X = 150;
			w5.Y = 210;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.botScore = new global::Gtk.Label();
			this.botScore.WidthRequest = 500;
			this.botScore.HeightRequest = 50;
			this.botScore.Name = "botScore";
			this.botScore.LabelProp = global::Mono.Unix.Catalog.GetString("label35");
			this.botScore.Justify = ((global::Gtk.Justification)(2));
			this.fixed4.Add(this.botScore);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.botScore]));
			w6.X = 150;
			w6.Y = 260;
			this.Add(this.fixed4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.playAgainBtn.Clicked += new global::System.EventHandler(this.ClickToPlayAgain);
			this.quitBtn.Clicked += new global::System.EventHandler(this.ClickToExit);
		}
	}
}
